### ISSUE TITLE
UserClaimParser Sample

### ISSUE THREAD

**Issue by filipecarneiro** [MultiTenancyServer/MultiTenancyServer#10]
Hi,

I’m trying the UserClaimParser but maybe I’m doing something wrong. Is there a sample for that?

I’ve added .AddClaimParser("http://schemas.microsoft.com/identity/claims/tenantid") to ConfigureServices and I’ve added a user programaticly with a claim with the same type and with the value “tenant1”.

After login with that user, I would expect to have the TenancyContext.Tenant with the tenant of the same CanonicalName. But Tenant is null…

What I’m missing?
Thank you.

**Comment by krispenner** [comment]
Hi @filipecarneiro,

I don't recall how I had that one working before, I had only quickly tested each parser once to ensure it grabbed a tenant.

My examples expect users to belong to a tenant, not globally, so this requires that we know the current tenant of the request prior to authenticating a user. However, in your case, you need to authenticate the user first, and then determine the tenant from their claims.

So I believe the issue may be due to the order in which your middleware is added to the HTTP pipeline. If you copied the example code, then the Authentication middleware is added after MultiTenancyServer. This causes the user to be null when the UserClaimParser executes and so there are no claims to compare. I would ensure you are running the Authentication middleware prior to MultiTenancyServer middleware and see if that helps.

Example:
```cs
public void Configure(IApplicationBuilder app)
{
    app.UseStaticFiles();
    app.UseAuthentication();
    app.UseMultiTenancy<Tenant>();
    app.UseMvcWithDefaultRoute();
}
```

Let me know if that helps.

**Comment by filipecarneiro** [comment]
That was it!
Changing the order of the middleware was the key 😊
Thank you!
