### ISSUE TITLE
How do you use this library when your model uses `long` primary keys

### ISSUE THREAD

**Issue by tonymobster** [MultiTenancyServer/MultiTenancyServer#2]
My models use `long` primary keys. I'm unable to configure multitenancy in my EF entities due to this constraint `where TKey : IEquatable<TKey>`.  Adding a migration results in the error: "The binary operator NotEqual is not defined for the types 'System.Int64' and 'System.Object'."

**Comment by krispenner** [comment]
Hi @tonymobster, I had not tested using `long `since I refactored the dynamic LINQ expressions for the EF query filters. There was an issue in the dynamic expressions that compared a long to null and this was failing the query. This has since been fixed in version 0.9.0 today.

Also, I have provided a full implementation of using a long (Int64) as keys in the int64identity branch of the Samples repo. You can easily see what the diff is compared to the string based sample here:

https://github.com/MultiTenancyServer/MultiTenancyServer.Samples/compare/int64identity

Note this line should now return an `object `and not your key type:
`private object _tenantId => _tenancyContext?.Tenant?.Id;`
https://github.com/MultiTenancyServer/MultiTenancyServer.Samples/blob/723a675b9c9b7cd0970daba8056eec2ad05fa774/src/AspNetIdentityAndEFCore/Data/ApplicationDbContext.cs#L20

I hope that can help you, any questions let me know.

**Comment by tonymobster** [comment]
Great. I'll test it out within the week and revert. Appreciate the quick response.

**Comment by tonymobster** [comment]
Hi, I just realized I never got back. I tested it and it's working great. Thanks a lot.
