### ISSUE TITLE
What are the supported database models?

### ISSUE THREAD

**Issue by mrsuau627** [MultiTenancyServer/MultiTenancyServer#5]
Hi, I'm looking into using your package in a web api project that I'm building. 
Does this only support a single, shared database for the multiple tenants or can it support a database per tenant? Is there a separate db connection per tenant?
Thanks!

**Comment by krispenner** [comment]
It can support this. Assuming you are using EF Core, you can simply supply the tenant specific database connection string in the OnConfiguring override of the context class. You would need some central config or database that maps a tenant ID to a database and expose that possibly through an IDatabaseConnectionStringRepository interface. I have played with this myself before and it worked but I don't know where that code went. It was pretty simple and something like the snippet below.
```
public class ApplicationDbContext : DbContext
{
    private readonly IDatabaseConnectionStringRepository _dbConnectionStringRepository;
    private readonly ITenancyContext<ApplicationTenant> _tenancyContext;

    public ApplicationDbContext(
        DbContextOptions<ApplicationDbContext> options,
        IDatabaseConnectionStringRepository dbConnectionStringRepository,
        ITenancyContext<ApplicationTenant> tenancyContext)
        : base(options)
    {
        _dbConnectionStringRepository = dbConnectionStringRepository;
        _tenancyContext = tenancyContext;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);

        var tenant = _tenancyContext.Tenant;
        var connectionString = _dbConnectionStringRepository.GetConnectionStringForTenant(tenant.Id);
        optionsBuilder.UseSqlServer(connectionString);
    }
}
```

Or, if it's just the database name that is different and it maps directly to the tenant ID, you could do something like:
```
public class ApplicationDbContext : DbContext
{
    private readonly ITenancyContext<ApplicationTenant> _tenancyContext;

    public ApplicationDbContext(
        DbContextOptions<ApplicationDbContext> options,
        ITenancyContext<ApplicationTenant> tenancyContext)
        : base(options)
    {
        _tenancyContext = tenancyContext;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);

        var tenantId = _tenancyContext?.Tenant?.Id;
        if (tenantId == null)
        {
            return;
        }

        var options = optionsBuilder.Options.FindExtension<Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal.SqlServerOptionsExtension>();
        if (options == null)
        {
            return;
        }

        // where the connection string was originally registered similar to: 
        // "Server=localhost; Database=tenant-{{TENANT_ID}}; User=user1; ..."
        var connectionString = options.ConnectionString.Replace("{{TENANT_ID}}", tenantId);
        optionsBuilder.UseSqlServer(connectionString);
    }
}
```

**Comment by krispenner** [comment]
I added a quick sample project that does just this, it has a ManagementDbContext which contains all tenants and each tenant has a DatabaseName property set (you could also just use the tenant's ID or CanonicalName if you wish). Then there is the ApplicationDbContext which is very basic, it requires no TenantId columns to be added as the database is for the one tenant, it merely adjusts the connection string to point to the database specified for the tenant. This could be cleaned up a bit more and have an IApplicationDbContextFactory that is registered and creates the correct context the first time rather than having to re-configure the options but this works well regardless.

https://github.com/MultiTenancyServer/MultiTenancyServer.Samples/tree/master/src/DatabasePerTenantAspIdAndEF

Hope that helps!

**Comment by mrsuau627** [comment]
Thanks for clearing this up! This helps a lot.
